[package]
name = "tiny-lru"
version = "0.1.0"
edition = "2024"
authors = ["Snehal Koukuntla <snehalreddyk@gmail.com>"]
description = "A Fast Small-then-Spill LRU cache"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/tiny-lru"
keywords = ["lru", "cache", "performance", "embedded", "hft"]
categories = ["data-structures", "caching"]

[features]
default = ["std"]
std = []

[dependencies]
tinyvec = "1"
hashbrown = { version = "0.14", default-features = true }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false
